---
book:
  title: My Book
  authors:
    - Your name here
  editors:
    - Any editors
  template: assets/templates/template.html.erb

generator:
  input: GFM
  enable_coderay: true
  coderay_css: class
  coderay_line_numbers: inline
